version: '3.8'

services:
  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'
    environment:
      MONGODB_URI: "mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo:27017/tmdb_movies?authSource=admin"
      REDIS_URI: "redis://redis:6379"
      ENABLE_WRITING_HANDLERS: 'false'
    depends_on:
      - mongo
      - redis
    networks:
      - api-network
      - db-network

  mongo:
    image: mongo:8.0-rc
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD}"
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'
    networks:
      - db-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - api-network

volumes:
  mongo_data:

networks:
  api-network:
  db-network:



