version: '3.8'

services:
  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'
    environment:
      MONGODB_URI: "mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo:27017"
      REDIS_URI: "redis://redis:6379"
      ENABLE_WRITING_HANDLERS: 'false'
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:8.0-rc
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD}"
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'

  mongo-express:
    image: mongo-express:1.0-20-alpine3.19
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGODB_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGODB_PASSWORD}"
      ME_CONFIG_MONGODB_SERVER: "mongo"
    ports:
      - '8081:8081'
    depends_on:
      - mongo

volumes:
  mongo_data:
